/**
 * CopilotMessageBadge.tsx — Pink Badge for Copilot System Messages
 *
 * Renders copilot-originated system messages with a distinctive pink pill
 * instead of the default grey system message styling. This makes it
 * immediately obvious which messages are from the autonomous copilot
 * vs. regular system notifications.
 *
 * Detection logic: A message is considered a copilot message if its role
 * is 'system' AND its content starts with the copilot message prefix
 * (🤖 emoji, defined in COPILOT_UI_LABELS.copilotMessagePrefix).
 *
 * The component strips the prefix emoji from the rendered text and replaces
 * it with a bold pink "COPILOT" label.
 *
 * Used by:
 *   - src/components/ui/CWFChatPanel.tsx (replaces inline system message rendering)
 */

import { COPILOT_THEME, COPILOT_UI_LABELS } from "../../../lib/params/copilot";

// =============================================================================
// HELPER — COPILOT MESSAGE DETECTION
// =============================================================================

/**
 * Check whether a system message was generated by the copilot engine.
 *
 * @param content - The raw message content string.
 * @returns true if the message starts with the copilot emoji prefix (🤖).
 */
export function isCopilotMessage(content: string): boolean {
  return content.startsWith(COPILOT_UI_LABELS.copilotMessagePrefix);
}

/**
 * Strip the copilot emoji prefix from a message for display purposes.
 * The badge label replaces the emoji, so we remove it to avoid duplication.
 *
 * @param content - The raw message content string.
 * @returns The message without the leading 🤖 and any trailing whitespace.
 */
export function stripCopilotPrefix(content: string): string {
  /** Build a regex that matches the prefix emoji + optional whitespace */
  const prefix = COPILOT_UI_LABELS.copilotMessagePrefix;
  return content.replace(new RegExp(`^${prefix}\\s*`), "");
}

// =============================================================================
// PROPS INTERFACE
// =============================================================================

/**
 * Props accepted by the CopilotMessageBadge component.
 * Only the raw message content is needed — the component handles
 * prefix detection and stripping internally.
 */
interface CopilotMessageBadgeProps {
  /** The raw system message content (may include 🤖 prefix) */
  content: string;
  /** Whether this message has an error flag (overrides copilot styling) */
  isError?: boolean;
}

// =============================================================================
// COMPONENT
// =============================================================================

/**
 * CopilotMessageBadge — Renders a system message pill with copilot styling.
 *
 * If the message is a copilot message (starts with 🤖), it renders with:
 *   - Pink background + pink border + glow shadow
 *   - Bold "COPILOT" label before the message text
 * Otherwise, it falls back to the standard system message styling.
 *
 * @param props - See CopilotMessageBadgeProps interface above.
 * @returns React element — a centered pill-shaped message element.
 */
export function CopilotMessageBadge({
  content,
  isError = false,
}: CopilotMessageBadgeProps) {
  /** Detect whether this is a copilot-originated message */
  const isCopilot = isCopilotMessage(content);

  /**
   * Determine the CSS classes for the pill based on state:
   * - Error: red styling (overrides everything)
   * - Copilot: pink styling with glow
   * - Default: subtle grey styling
   */
  const pillClassName = `text-xs px-3 py-1.5 rounded-full ${
    isError
      ? "bg-red-500/20 text-red-300 border border-red-500/30"
      : isCopilot
        ? "bg-pink-500/15 text-pink-300 border border-pink-500/30"
        : "bg-white/5 text-white/40 border border-white/10"
  }`;

  /** Add glow shadow for copilot messages (subtle pink radiance) */
  const pillStyle = isCopilot
    ? { boxShadow: `0 0 8px ${COPILOT_THEME.messageBg}` }
    : {};

  return (
    <div className="flex justify-center my-2">
      {/* Centered pill container */}
      <div className={pillClassName} style={pillStyle}>
        {/* Copilot badge label — only shown for copilot messages */}
        {isCopilot && (
          <span
            className="font-bold mr-1"
            style={{ color: COPILOT_THEME.primaryLight }}
          >
            {COPILOT_UI_LABELS.messageBadgeLabel}
          </span>
        )}
        {/* Message text — stripped of prefix emoji for copilot messages */}
        {isCopilot ? stripCopilotPrefix(content) : content}
      </div>
    </div>
  );
}
