/**
 * exporter.js — TypeScript Code Generation and Export Modal
 *
 * Reads the current editor state and produces a TypeScript code string
 * that can be copy-pasted directly into the ctaSteps[] arrays in demoScript.ts.
 *
 * Depends on: schema.js, editor.js (must be loaded first)
 */

// ─── TypeScript Generation ────────────────────────────────────────────────────

/**
 * generateAllTypeScript — builds one ctaSteps block per stage.
 * Only emits fields that contain a meaningful value (skips empty defaults).
 */
function generateAllTypeScript() {
    const state = window.getEditorState();
    const out = [];

    out.push('// ════════════════════════════════════════════════════════════════════');
    out.push('// Auto-generated by VF Demo Script Editor');
    out.push('// Paste each ctaSteps block into the matching act in demoScript.ts');
    out.push('// ════════════════════════════════════════════════════════════════════');
    out.push('');

    STAGES.forEach(function (stage) {
        const steps = state.stages[stage.id].steps;
        out.push('// ── ' + stage.emoji + ' ' + stage.label + " (id: '" + stage.id + "') ─────────────────────────────");
        out.push('ctaSteps: [');
        steps.forEach(function (step, i) {
            out.push('    { // Click #' + (i + 1));
            buildStepFields(step).forEach(function (line) { out.push('        ' + line); });
            out.push('    },');
        });
        out.push('],');
        out.push('');
    });

    return out.join('\n');
}

/**
 * buildStepFields — converts one step object into an array of TypeScript lines.
 * Fields with empty/default values are omitted for cleanliness.
 */
function buildStepFields(step) {
    const lines = [];

    if (step.ctaLabel && step.ctaLabel.trim())
        lines.push('ctaLabel: ' + q(step.ctaLabel) + ',');

    if (step.slideImageUrl && !step.mediaInstruction)
        lines.push('slideImageUrl: ' + q(step.slideImageUrl) + ',');

    // mediaInstruction takes priority over slideImageUrl when both are set
    if (step.mediaInstruction)
        lines.push('mediaInstruction: ' + q(step.mediaInstruction) + ',');

    if (step.scenarioCode)
        lines.push('scenarioCode: ' + q(step.scenarioCode) + ',');

    if (step.workOrderId)
        lines.push('workOrderId: ' + q(step.workOrderId) + ',');

    if (step.delayMs !== '' && step.delayMs !== null && step.delayMs !== undefined)
        lines.push('delayMs: ' + Number(step.delayMs) + ',');

    if (step.screenText && step.screenText.trim())
        lines.push('screenText: ' + bt(step.screenText.trim()) + ',');

    // Formatting fields — only emit when they differ from defaults
    if (step.screenTextAlign && step.screenTextAlign !== 'center')
        lines.push("screenTextAlign: '" + step.screenTextAlign + "',");
    if (step.screenTextWeight && step.screenTextWeight !== 'bold')
        lines.push("screenTextWeight: '" + step.screenTextWeight + "',");
    if (step.screenTextSize && step.screenTextSize !== 'lg')
        lines.push("screenTextSize: '" + step.screenTextSize + "',");

    if (step.ariaLocal && step.ariaLocal.trim())
        lines.push('ariaLocal: ' + bt(step.ariaLocal.trim()) + ',');

    // ariaLocal formatting — only emit non-defaults (left/normal/md)
    if (step.ariaLocalAlign && step.ariaLocalAlign !== 'left')
        lines.push("ariaLocalAlign: '" + step.ariaLocalAlign + "',");
    if (step.ariaLocalWeight && step.ariaLocalWeight !== 'normal')
        lines.push("ariaLocalWeight: '" + step.ariaLocalWeight + "',");
    if (step.ariaLocalSize && step.ariaLocalSize !== 'md')
        lines.push("ariaLocalSize: '" + step.ariaLocalSize + "',");

    if (step.ariaApi && step.ariaApi.trim())
        lines.push('ariaApi: ' + bt(step.ariaApi.trim()) + ',');

    // ariaApi formatting — only emit non-defaults (left/normal/md)
    if (step.ariaApiAlign && step.ariaApiAlign !== 'left')
        lines.push("ariaApiAlign: '" + step.ariaApiAlign + "',");
    if (step.ariaApiWeight && step.ariaApiWeight !== 'normal')
        lines.push("ariaApiWeight: '" + step.ariaApiWeight + "',");
    if (step.ariaApiSize && step.ariaApiSize !== 'md')
        lines.push("ariaApiSize: '" + step.ariaApiSize + "',");

    // Always emit ariaInputEnabled — it is a meaningful boolean flag
    lines.push('ariaInputEnabled: ' + (step.ariaInputEnabled ? 'true' : 'false') + ',');

    // Panel actions — only emit panels that have a state set
    const panels = PANELS.filter(function (p) {
        return step.panelActions[p.id] === 'open' || step.panelActions[p.id] === 'close';
    });
    if (panels.length > 0) {
        lines.push('panelActions: [');
        panels.forEach(function (p) {
            lines.push("    { panel: '" + p.id + "', state: '" + step.panelActions[p.id] + "' },");
        });
        lines.push('],');
    }

    if (step.simulationAction)
        lines.push("simulationAction: '" + step.simulationAction + "',");

    if (step.transitionTo)
        lines.push('transitionTo: ' + q(step.transitionTo) + ',');

    if (lines.length === 0)
        lines.push('// (empty step — no fields configured yet)');

    return lines;
}

/**
 * q — wraps a string in single quotes for short, single-line fields (ctaLabel, slideImageUrl, etc.).
 * Escapes backslashes and single quotes, but NOT newlines.
 * For any field that may contain newlines, use bt() instead.
 */
function q(str) {
    return "'" + String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

/**
 * bt — wraps a string in backtick template literals for multi-line capable fields.
 * Used for: screenText, ariaLocal, ariaApi — any field where the presenter may
 * write multi-line content or use inline commands like <cls>, <w:N>, etc.
 *
 * Escaping rules for template literals:
 *   - Backtick ` must become \`
 *   - ${  must become \${ (prevents template interpolation)
 *   - Backslashes are kept as-is so \n in the text stays as \n in the output
 */
function bt(str) {
    var escaped = String(str)
        .replace(/`/g, '\\`')          // escape backtick
        .replace(/\$\{/g, '\\${');    // escape template interpolation
    return '`' + escaped + '`';
}

// ─── Export Modal ─────────────────────────────────────────────────────────────

/**
 * showExportModal — generates TypeScript and displays it in the overlay modal.
 * Exposed on window so editor.js can call it from the Export button.
 */
window.showExportModal = function () {
    const code = generateAllTypeScript();
    document.getElementById('export-code').textContent = code;
    document.getElementById('export-modal').classList.add('visible');
};

/** hideExportModal — closes the export overlay */
window.hideExportModal = function () {
    document.getElementById('export-modal').classList.remove('visible');
};

/** copyToClipboard — writes generated code to the system clipboard */
window.copyToClipboard = function () {
    const code = document.getElementById('export-code').textContent;
    navigator.clipboard.writeText(code).then(function () {
        const btn = document.getElementById('btn-copy');
        const orig = btn.textContent;
        btn.textContent = '✓ Copied!';
        btn.style.background = 'rgba(34,197,94,0.3)';
        setTimeout(function () { btn.textContent = orig; btn.style.background = ''; }, 2000);
    });
};

// ─── Modal event wiring ───────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('btn-close-modal').addEventListener('click', window.hideExportModal);
    document.getElementById('btn-copy').addEventListener('click', window.copyToClipboard);
    // Close on backdrop click
    document.getElementById('export-modal').addEventListener('click', function (e) {
        if (e.target === e.currentTarget) window.hideExportModal();
    });
});
