/**
 * SimulationSessionInfo.tsx — Session Info Display
 *
 * Shows both:
 *  - The master session UUID (from simulationStore)
 *  - The data store's 6-character session code (from simulationDataStore)
 *
 * The session code is generated by the Supabase-synced data store and
 * provides a short, shareable identifier for the simulation run.
 *
 * Hidden on mobile (sm:flex). Uses monospace font and tabular-nums
 * for consistent digit alignment.
 *
 * Used by: Header.tsx
 */
import { useSimulationStore } from "../../store/simulationStore";
import { useSimulationSession } from "../../hooks/useSimulation";

export const SimulationSessionInfo = () => {
  const sessionId = useSimulationStore((s) => s.sessionId);
  const { sessionCode } = useSimulationSession();

  return (
    <div className="flex items-center gap-1 sm:gap-1.5 px-1 py-0.5">
      {/* Session Code Badge (from data store) */}
      {sessionCode && (
        <>
          <span className="text-[0.625rem] sm:text-xs text-emerald-400/70">
            CODE
          </span>
          <span className="font-mono text-[0.625rem] sm:text-sm font-bold text-emerald-400 tabular-nums tracking-wider">
            {sessionCode}
          </span>
          <span className="text-white/20 mx-0.5">|</span>
        </>
      )}
      {/* Master Session ID */}
      <span className="text-[0.625rem] sm:text-xs text-emerald-400/70">ID</span>
      <span className="font-mono text-[0.625rem] sm:text-sm font-bold text-white/60 tabular-nums tracking-wider">
        {sessionId}
      </span>
    </div>
  );
};
